# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - env:
      global:
        - CODECOV_TOKEN="a8d89a6f-9351-459a-8e3c-aed3aa8f9fd2"
        - CODECOV_TOKEN='ef408feb-8386-46c6-9683-f01b49eeae32'

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - FaJlJleN@ya.ru
    on_success: never # default: change
    on_failure: always # default: always

    env:
        global:
          - CODECOV_TOKEN="a8d89a6f-9351-459a-8e3c-aed3aa8f9fd2"
          - CODECOV_TOKEN='ef408feb-8386-46c6-9683-f01b49eeae32'